blog/urls.py
from django.urls import path
from .import views
app_name="blog"
urlpatterns=[
    path("",views.blog_list,name="blog_list"),
    path("<int:id>",views.blog_detail,name="blog_detail"),
    path("tag/<slug:tag>",views.blog_tag,name="blog_tag"),
    path("category/<slug:category>",views.blog_category,name="blog_category"),
    path("search/",views.search,name="search")

]

foods/urls.py
from django.urls import path
from .import views
app_name ="foods"
urlpatterns=[
    path("",views.food_list,name="food_list"),
    path("<int:id>",views.food_detail,name="detail"),
    path("menu/",views.menu,name="menu"),
    path("galary/",views.galary,name="galary"),
    

]

reservation/urls.py
from django.urls import path
from .import views

app_name='reservation'
urlpatterns=[
    path("",views.reserve,name="book")
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path,include
from django .conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('foods.urls')),
    path('book/', include('reservation.urls')),
    path('blog/', include('blog.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),

   

]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

foods/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.

class Food(models.Model):
    FOOD_TYPE=[
        ("breakfast","صبحانه"),
        ("drink","نوشیدنی"),
        ("dinner","شام"),
        ("lunch","ناهار")
    ]
    name=models.CharField(max_length=100)
    description= models.CharField(_("توضیحات"),max_length=50)
    rate=models.IntegerField(_("امتیاز"), default=0)
    price=models.IntegerField()
    time=models.IntegerField(_("زمان لازم"))
    pub_date=models.DateField(_("تاریخ انتشار"),auto_now=False,auto_now_add=True)
    photo=models.ImageField(upload_to= 'foods/')
    type_food=models.CharField(_("نوع غذا"),max_length=10,choices=FOOD_TYPE,default="dinner")

    def __str__(self):
        return self.name


class Galery(models.Model):
    photo=models.ImageField(upload_to= 'galery/')

foods/views.py
from django.shortcuts import render
from .models import Food,Galery


# Create your views here.
def food_list(request):
    food_list=Food.objects.all()
    galer=Galery.objects.all()
    context={"foods": food_list,"galery":galer}
    return render(request,"foods/list.html",context)

def food_detail(request,id):
    food=Food.objects.get(id=id)
    context={"food":food}
    return render(request,"foods/detail.html",context)

def menu(request):
    food_list=Food.objects.all()
    
    context={"foods": food_list}
    return render(request,"foods/menu.html",context)
def galary(request):
    galer=Galery.objects.all()
    context={"galery":galer}
    return render(request,"foods/galary.html",context)

foods/templates/foods/detail.html
{% extends 'base.html' %} {% load static %} {% block content %}

<style>
    h3 {
        margin-left: 10%;
    }
    
    img {
        align-content: center;
    }
</style>

</head>

<body>
    <br>
    <br>
    <br>
    <img src='{{food.photo.url}}'>
    <br>
    <br>
    <h3>Name: {{food.name}} </h3>
    <h3>Price: {{food.price}} $ </h3>



    {% endblock content %}

foods/templates/foods/galary.html
{% extends 'base.html' %} {% load static %} {% block content %}
<!-- Start Gallery -->
<div class="gallery-box">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading-title text-center">
                    <h2>Gallery</h2>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
                </div>
            </div>
        </div>
        <div class="tz-gallery">
            <div class="row">
                {% for gal in galery %}
                <div class="col-sm-12 col-md-4 col-lg-4">
                    <a class="lightbox" href="images/gallery-img-01.jpg">
                        <img class="img-fluid" src="{{gal.photo.url}}" style="height: 350px;" alt="Gallery Images">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<!-- End Gallery -->


{% endblock content %}

foods/templates/foods/list.html
 {% extends 'base.html' %} {% load static %} {% block content %}



<!-- Start slides -->
<div id="slides" class="cover-slides">
    <ul class="slides-container">
        <li class="text-center">
            <img src="{% static 'images/slider-01.jpg' %}" alt="">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="m-b-20"><strong>Welcome To <br> Yamifood Restaurant</strong></h1>
                        <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                        <p><a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'reservation:book' %}">Reservation</a></p>
                    </div>
                </div>
            </div>
        </li>
        <li class="text-center">
            <img src="{% static 'images/slider-02.jpg' %}" alt="">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="m-b-20"><strong>Welcome To <br> Yamifood Restaurant</strong></h1>
                        <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                        <p><a class="btn btn-lg btn-circle btn-outline-new-white" href="#">Reservation</a></p>
                    </div>
                </div>
            </div>
        </li>
        <li class="text-center">
            <img src="{% static 'images/slider-03.jpg' %}" alt="">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="m-b-20"><strong>Welcome To <br> Yamifood Restaurant</strong></h1>
                        <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                        <p><a class="btn btn-lg btn-circle btn-outline-new-white" href="#">Reservation</a></p>
                    </div>
                </div>
            </div>
        </li>
    </ul>
    <div class="slides-navigation">
        <a href="#" class="next"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
        <a href="#" class="prev"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
    </div>
</div>
<!-- End slides -->

<!-- Start About -->
<div class="about-section-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12">
                <img src="{% static 'images/about-img.jpg' %}" alt="" class="img-fluid">
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 text-center">
                <div class="inner-column">
                    <h1>Welcome To <span>Yamifood Restaurant</span></h1>
                    <h4>Little Story</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque auctor suscipit feugiat. Ut at pellentesque ante, sed convallis arcu. Nullam facilisis, eros in eleifend luctus, odio ante sodales augue, eget lacinia lectus erat
                        et sem. </p>
                    <p>Sed semper orci sit amet porta placerat. Etiam quis finibus eros. Sed aliquam metus lorem, a pellentesque tellus pretium a. Nulla placerat elit in justo vestibulum, et maximus sem pulvinar.</p>
                    <a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'reservation:book' %}">Reservation</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End About -->

<!-- Start QT -->
<div class="qt-box qt-background">
    <div class="container">
        <div class="row">
            <div class="col-md-8 ml-auto mr-auto text-left">
                <p class="lead ">
                    " If you're not the one cooking, stay out of the way and compliment the chef. "
                </p>
                <span class="lead">Michael Strahan</span>
            </div>
        </div>
    </div>
</div>
<!-- End QT -->

<!-- Start Menu -->
<div class="menu-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading-title text-center">
                    <h2>Special Menu</h2>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="special-menu text-center">
                    <div class="button-group filter-button-group">
                        <button class="active" data-filter="*">All</button>
                        <button data-filter=".drink">Drinks</button>
                        <button data-filter=".lunch">Lunch</button>
                        <button data-filter=".dinner">Dinner</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="row special-list">
            {% for food in foods %}
            <a href="{% url 'foods:detail' food.id %}">
                <div class="col-lg-4 col-md-6 special-grid {{food.type_food}}">

                    <div class="gallery-single fix">

                        <img src="{{food.photo.url}}" style="height:280px; " class="img-fluid" alt="Image">
                        <div class="why-text">
                            <h4>{{food.name}}</h4>
                            <p>{{food.description}}</p>
                            <h5>Price = {{food.price}} $</h5>
                        </div>

                    </div>


                </div>
            </a>
            {% endfor %}


        </div>

    </div>
</div>
<!-- End Menu -->

<!-- Start Gallery -->
<div class="gallery-box">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading-title text-center">
                    <h2>Gallery</h2>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
                </div>
            </div>
        </div>
        <div class="tz-gallery">
            <div class="row">
                {% for gal in galery %}
                <div class="col-sm-12 col-md-4 col-lg-4">
                    <a class="lightbox" href="images/gallery-img-01.jpg">
                        <img class="img-fluid" src="{{gal.photo.url}}" style="height: 350px;" alt="Gallery Images">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<!-- End Gallery -->



<!-- Start Contact info -->
<div class="contact-imfo-box">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <i class="fa fa-volume-control-phone"></i>
                <div class="overflow-hidden">
                    <h4>Phone</h4>
                    <p class="lead">
                        +01 123-456-4590
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                <i class="fa fa-envelope"></i>
                <div class="overflow-hidden">
                    <h4>Email</h4>
                    <p class="lead">
                        yourmail@gmail.com
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                <i class="fa fa-map-marker"></i>
                <div class="overflow-hidden">
                    <h4>Location</h4>
                    <p class="lead">
                        800, Lorem Street, US
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Contact info -->



{% endblock content %}

foods/templates/foods/menu.html
{% extends 'base.html'%} {% load static %} {% block content %}
<!-- Start All Pages -->
<div class="all-page-title page-breadcrumb">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1>Special Menu</h1>
            </div>
        </div>
    </div>
</div>
<!-- End All Pages -->
<!-- Start Menu -->
<div class="menu-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading-title text-center">
                    <h2>Special Menu</h2>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="special-menu text-center">
                    <div class="button-group filter-button-group">
                        <button class="active" data-filter="*">All</button>
                        <button data-filter=".drink">Drinks</button>
                        <button data-filter=".lunch">Lunch</button>
                        <button data-filter=".dinner">Dinner</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="row special-list">
            {% for food in foods %}
            <a href="{% url 'foods:detail' food.id %}">
                <div class="col-lg-4 col-md-6 special-grid {{food.type_food}}">

                    <div class="gallery-single fix">

                        <img src="{{food.photo.url}}" style="height:280px; " class="img-fluid" alt="Image">
                        <div class="why-text">
                            <h4>{{food.name}}</h4>
                            <p>{{food.description}}</p>
                            <h5>Price = {{food.price}} $</h5>
                        </div>

                    </div>


                </div>
            </a>
            {% endfor %}


        </div>

    </div>
</div>
<!-- End Menu -->
{% endblock content %}