blog/urls.py
from django.urls import path
from .import views
app_name="blog"
urlpatterns=[
    path("",views.blog_list,name="blog_list"),
    path("<int:id>",views.blog_detail,name="blog_detail"),
    path("tag/<slug:tag>",views.blog_tag,name="blog_tag"),
    path("category/<slug:category>",views.blog_category,name="blog_category"),
    path("search/",views.search,name="search")

]

restaurant/urls.py
from django.contrib import admin
from django.urls import path,include
from django .conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('foods.urls')),
    path('book/', include('reservation.urls')),
    path('blog/', include('blog.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),

   

]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from ckeditor.fields import RichTextField


class Blog(models.Model):
    title=models.CharField(_("عنوان"),max_length=50)
    description= models.CharField(_("توضیحات"),max_length=100)
    content= models.TextField(_("متن"))
    created_at=models.DateField(_("زمان انتشار"),default= timezone.now)
    author=models.ForeignKey(User,verbose_name=_("نویسنده"),on_delete=models.CASCADE )
    image= models.ImageField(_("تصویر"),upload_to= "blog/",blank=True,null=True)
    category=models.ForeignKey("Category",related_name="blog",verbose_name=_("دسته بندی"),on_delete=models.CASCADE , blank=True,null=True)
    tags=models.ManyToManyField("tag",verbose_name=_("تگ ها"),related_name="blogs",blank=True,null=True)
    def __str__(self):
        return self.title

class Category(models.Model):
    title=models.CharField(_("عنوان"),max_length=50)
    slug=models.SlugField(_("عنوان لاتین"))
    published_at=models.DateField(_("تاریخ انتشار"),auto_now=False,auto_now_add=True)
    def __str__(self):
        return self.title

class Tag(models.Model):
    title=models.CharField(_("عنوان"),max_length=50)
    slug=models.SlugField(_("عنوان لاتین"))
    published_at=models.DateField(_("تاریخ انتشار"),auto_now=False,auto_now_add=True)
    updated_at=models.DateField(_("تاریخ انتشار"),auto_now=True,auto_now_add=False)
    def __str__(self):
        return self.title
class Comments(models.Model):
    blog=models.ForeignKey("Blog",verbose_name=_("مقاله"),related_name="comments",on_delete=models.CASCADE)
    name=models.CharField(_("نام کاربر"),max_length=100)
    email=models.EmailField(_("آدرس الکترونیکی"),max_length=254)
    message=models.TextField(_("متن پیام"))
    date=models.DateField(_("تاریخ نشر"),auto_now=False,auto_now_add=True)
    def __str__(self):
        return self.email

blog/forms.py
from django import forms



class CommentForm(forms.Form):
    name=forms.CharField(max_length=100)
    email=forms.EmailField(max_length=254)
    message=forms.CharField(widget=forms.Textarea)
    

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog,Tag,Category,Comments
from .forms import CommentForm
from django.core.paginator import Paginator


# Create your views here.
def blog_list(request):
    blogs=Blog.objects.all()
    paginator = Paginator(blogs,3) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    blog_list = paginator.get_page(page_number)
    context={
        "blog_list":blog_list
    }
    return render(request,"blogs/blog_list.html",context)

def blog_detail(request,id):
    blog=Blog.objects.get(id=id)
    tags=Tag.objects.all().filter(blogs=blog)
    recents=Blog.objects.all().order_by("-created_at")[:1]
    categories=Category.objects.all()
    comments=Comments.objects.all().filter(blog=blog)

    if request.method=="POST":
        form=CommentForm(request.POST)
        if form.is_valid():
            new_name=form.cleaned_data["name"]
            new_email=form.cleaned_data["email"]
            new_message=form.cleaned_data["message"]
            new_comment=Comments(blog=blog,name=new_name,email=new_email,message=new_message)
            new_comment.save()
    context={
        "blog":blog,
        "tags":tags,
        "recents":recents,
        "categories":categories,
        "comments":comments
    }
    return render(request,"blogs/blog_detail.html",context)
def blog_tag(request,tag):
    blog_list=Blog.objects.all().filter(tags__slug=tag)
    context={
        "blog_list":blog_list
    }
    return render(request,"blogs/blog_list.html",context)
    
def blog_category(request,category):
    blog_list=Blog.objects.all().filter(category__slug=category)
    context={
        "blog_list":blog_list
    }
    return render(request,"blogs/blog_list.html",context)
def search(request):
    if request.method=="GET":
        q=request.GET.get("search") 
        blog_list=Blog.objects.all().filter(title__icontains=q)  
        return render(request,"blogs/blog_list.html",{"blog_list":blog_list})

blog/templates/blogs/blog_detail.html
 {% extends 'base.html' %} {% load static %} {% block content %}
<!-- Start All Pages -->
<div class="all-page-title page-breadcrumb">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1>Blog</h1>
            </div>
        </div>
    </div>
</div>
<!-- End All Pages -->

<!-- Start blog details -->
<div class="blog-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading-title text-center">
                    <h2>{{blog.title}}</h2>
                    <p>{{blog.description}}</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-8 col-lg-8 col-12">
                <div class="blog-inner-details-page">
                    <div class="blog-inner-box">
                        <div class="side-blog-img">
                            <img class="img-fluid" style="height: 400px; width:500px" src="{{blog.image.url}}" alt="">
                            <div class="date-blog-up">
                                27 Fab
                            </div>
                        </div>
                        <div class="inner-blog-detail details-page">
                            <h3>{{blog.description}}</h3>
                            <ul>
                                <li><i class="zmdi zmdi-account"></i>Posted By : <span>{{blog.author.first_name}} {{blog.author.last_name}}</span></li>
                                <li>|</li>
                                <li><i class="zmdi zmdi-time"></i>Date : <span>{{blog.created_at}}</span></li>
                            </ul>
                            <p style="text-align: right;" dir="rtl">{{blog.content}}.</p>

                        </div>
                    </div>
                    <div class="blog-comment-box">
                        <h3>نظرات</h3>
                        {% for cm in comments %}
                        <div class="comment-item">
                            <div class="comment-item-left">
                                <img src="images/avt-img.jpg" alt="">
                            </div>
                            <div class="comment-item-right">
                                <div class="pull-left">
                                    <a href="#">{{cm.name}}</a>
                                </div>
                                <div class="pull-right">
                                    <i class="fa fa-clock-o" aria-hidden="true"></i>Date : <span>{{cm.date}}</span>
                                </div>
                                <div class="des-l">
                                    <p align="right">{{cm.message}}</p>
                                </div>
                                <!-- <a href="#" class="right-btn-re"><i class="fa fa-reply" aria-hidden="true"></i> Reply</a> -->
                            </div>
                        </div>
                        {% endfor %}
                        <!-- <div class="comment-item children">
                            <div class="comment-item-left">
                                <img src="images/avt-img.jpg" alt="">
                            </div>
                            <div class="comment-item-right">
                                <div class="pull-left">
                                    <a href="#">Admin</a>
                                </div>
                                <div class="pull-right">
                                    <i class="fa fa-clock-o" aria-hidden="true"></i>Time : <span>1.30 pm</span>
                                </div>
                                <div class="des-l">
                                    <p>Morbi lacinia ultrices lorem id tincidunt. Cras id dui risus. Pellentesque consectetur id mi sed pharetra. Proin imperdiet gravida nisl, sit amet varius urna. In auctor.</p>
                                </div>
                                <a href="#" class="right-btn-re"><i class="fa fa-reply" aria-hidden="true"></i> Reply</a>
                            </div>
                        </div> -->
                    </div>
                    <div class="comment-respond-box">
                        <h3>Leave your comment </h3>
                        <div class="comment-respond-form">
                            <form id="commentrespondform" class="comment-form-respond row" method="post">
                                {% csrf_token %}
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <input id="name_com" class="form-control" name="name" placeholder="Name" type="text">
                                    </div>
                                    <div class="form-group">
                                        <input id="email_com" class="form-control" name="email" placeholder="Your Email" type="email">
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <textarea class="form-control" name="message" id="textarea_com" placeholder="Your Message" rows="2"></textarea>
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <button class="btn btn-submit">Submit comment</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-4 col-lg-4 col-md-6 col-sm-8 col-12 blog-sidebar">
                <div class="right-side-blog">
                    <h3>Search</h3>
                    <form method="GET" action="{% url 'blog:search' %}">
                        <div class="blog-search-form">
                            <input name="search" placeholder="Search blog" type="text">
                            <button class="search-btn" type="submit">
								<i class="fa fa-search" aria-hidden="true"></i>
							</button>
                        </div>
                    </form>

                    <h3>Categories</h3>
                    <div class="blog-categories">
                        <ul>
                            {% for cat in categories %}
                            <li><a href="{% url 'blog:blog_category' cat.slug %}"><span>{{cat.title}}</span></a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <h3>Recent Post</h3>
                    <div class="post-box-blog">
                        <div class="recent-post-box">
                            {% for blog in recents %}
                            <div class="recent-box-blog">
                                <div class="recent-img">
                                    <img class="img-fluid" style="height: 50px;" src="{{blog.image.url}}" alt="">
                                </div>
                                <div class="recent-info">
                                    <ul>
                                        <li><i class="zmdi zmdi-account"></i>Posted By : <span>{{blog.author}}</span></li>
                                        <li>|</li>
                                        <li><i class="zmdi zmdi-time"></i>Date : <span>{{blog.created_at}}</span></li>
                                    </ul>
                                    <h4>{{blog.description}}</h4>
                                </div>
                            </div>
                            {% endfor %}


                        </div>
                    </div>
                    <h3>Recent Tag</h3>
                    <div class="blog-tag-box">
                        <ul class="list-inline tag-list">
                            {% for tag in tags %}
                            <li class="list-inline-item"><a href="{% url 'blog:blog_tag' tag.slug %}">{{tag.title}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<!-- End details -->

<!-- Start Contact info -->
<div class="contact-imfo-box">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <i class="fa fa-volume-control-phone"></i>
                <div class="overflow-hidden">
                    <h4>Phone</h4>
                    <p class="lead">
                        +01 123-456-4590
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                <i class="fa fa-envelope"></i>
                <div class="overflow-hidden">
                    <h4>Email</h4>
                    <p class="lead">
                        yourmail@gmail.com
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                <i class="fa fa-map-marker"></i>
                <div class="overflow-hidden">
                    <h4>Location</h4>
                    <p class="lead">
                        800, Lorem Street, US
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Contact info -->
{% endblock content %}

blog/templates/blogs/blog_list.html
{% extends 'base.html' %} {% load static %} {% block content %}
<!-- Start All Pages -->
<div class="all-page-title page-breadcrumb">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1>Blog</h1>
            </div>
        </div>
    </div>
</div>
<!-- End All Pages -->

<!-- Start blog -->
<div class="blog-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading-title text-center">
                    <h2>Blog</h2>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
                </div>
            </div>
        </div>
        <div class="row">
            {% for blog in blog_list %}
            <div class="col-lg-4 col-md-6 col-12">
                <div class="blog-box-inner">
                    <div class="blog-img-box">
                        <img class="img-fluid" style="height:430px" src="{{blog.image.url}}" alt="">
                    </div>
                    <div class="blog-detail">
                        <h4>{{blog.title}}</h4>
                        <ul>
                            <li><span>{{blog.author}}</span></li>
                            <li>|</li>
                            <li><span>{{blog.created_at| date:"Y b d"}}</span></li>
                        </ul>
                        <p>{{blog.content|truncatewords:50}} </p>

                        <a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'blog:blog_detail' blog.id %}">Read More</a>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</div>
<!-- End blog -->
<!-- paging -->
{% if blog_list.has_other_pages %}
<div class="container">
    <div class="row">
        <div class="col d-flex justify-content-center">
            <nav aria-label="Page navigation example">
                <ul class="pagination">

                    {% if blog_list.has_previous %}
                    <li class="page-item "><a class="page-link" href="?page=1">First</a></li>
                    <li class="page-item">
                        <a class="page-link" href="{{blog_list.previous_page_number}}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    {% endif %} {% for page in blog_list.paginator.page_range %} {% if blog_list.number == page %}
                    <li class="page-item active"><a class="page-link" href="?page={{page}} ">{{page}}</a></li>
                    {% else %}
                    <li class="page-item "><a class="page-link" href="?page={{page}}">{{page}}</a></li>
                    {%endif%} {% endfor %} {% if blog_list.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="{{blog_list.next_page_number}}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                    <li class="page-item "><a class="page-link" href="?page={{blog_list.paginator.num_pages}}">End</a></li>
                    {%endif%}
                </ul>
            </nav>

        </div>

    </div>
</div>
{% endif %}




<!-- Start Contact info -->
<div class="contact-imfo-box">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <i class="fa fa-volume-control-phone"></i>
                <div class="overflow-hidden">
                    <h4>Phone</h4>
                    <p class="lead">
                        +01 123-456-4590
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                <i class="fa fa-envelope"></i>
                <div class="overflow-hidden">
                    <h4>Email</h4>
                    <p class="lead">
                        yourmail@gmail.com
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                <i class="fa fa-map-marker"></i>
                <div class="overflow-hidden">
                    <h4>Location</h4>
                    <p class="lead">
                        800, Lorem Street, US
                    </p>
                </div>
            </div>
        </div>
    </div>
</div> {% endblock content %}



<!-- End Contact info -->